document.writeln("<footer>");
document.writeln("        <div class=\"brand-info\">");
document.writeln("            <div class=\"company-info\">");
document.writeln("                <h3>品牌介绍</h3>");
document.writeln("                <div class=\"dec\">");
document.writeln("                    <p>广场位于深圳罗湖区水贝商业圈中轴核心区，</p>");
document.writeln("                    <p>是深圳黄金珠宝产业聚集地最重要的交易、文化、信息交流平台。</p>");
document.writeln("                </div>");
document.writeln("                <p><i class=\"iconfont icondizhi\"></i>广场位于深圳罗湖区水贝商业圈中轴核心区</p>");
document.writeln("                <p><i class=\"iconfont iconStone-mail-open\"></i>*******@gmail.com</p>");
document.writeln("                <p><i class=\"iconfont icondianhua\"></i>0755-88888888</p>");
document.writeln("            </div>");
document.writeln("            <div class=\"map\">");
document.writeln("                <h3>分店分布</h3>");
document.writeln("                <img src=\"./src/images/index/index-map.jpg\" alt=\"\">");
document.writeln("            </div>");
document.writeln("            <div class=\"share\">");
document.writeln("                <h3>关注我们</h3>");
document.writeln("                <div>");
document.writeln("                    <i class=\"iconfont iconweixin\"></i>");
document.writeln("                    <i class=\"iconfont iconweibo\"></i>");
document.writeln("                </div>");
document.writeln("                <p>礼物，一种更完美的情感表达方式</p>");
document.writeln("                <div class=\"language\">");
document.writeln("                    <a href=\"#\">中文</a>");
document.writeln("                    <a href=\"#\">English</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"copyright\">");
document.writeln("            <p>版权所有 ©2018 北PPA珠宝股份有限公司 010-67133013 粤ICP备13022809号-1 京公网安备11010102001976</p>");
document.writeln("        </div>");
document.writeln("    </footer>");