document.writeln("<div class=\"nav-wrap\">");
document.writeln("        <div class=\"container\">");
document.writeln("            <div class=\"ppa-logo\">");
document.writeln("                <img src=\"./src/images/index/logo.jpg\" alt=\"PPA珠宝\">");
document.writeln("            </div>");
document.writeln("            <div class=\"nav-bar\">");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\"./index.html\">首页</a></li>");
document.writeln("                    <li><a href=\"http://www.baidu.com\" target=\"_top\">品牌介绍<i class=\"iconfont iconjiantou\"></i></a></li>");
document.writeln("                    <li><a href=\"#\">资讯中心<i class=\"iconfont iconjiantou\"></i></a></li>");
document.writeln("                    <li><a href=\"./products.html\">产品中心<i class=\"iconfont iconjiantou\"></i></a></li>");
document.writeln("                    <li><a href=\"#\">设计师频道<i class=\"iconfont iconjiantou\"></i></a></li>");
document.writeln("                    <li><a href=\"#\">联系我们<i class=\"iconfont iconjiantou\"></i></a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\"search\">");
document.writeln("                <a href=\"#\"><i class=\"iconfont iconfangdajing\"></i></a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");